name: b2b_mvp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.2
  asp: ^1.3.0
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  google_sign_in: ^6.2.1
  http: ^1.2.0
  logger: ^2.1.0
  carousel_slider: ^4.2.1
  icons_plus: ^5.0.0
  hive: ^2.2.3
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

